# Generated by Smolqwery on 2022-03-07T19:53:23.396681+00:00
from django.db import migrations

from smolqwery.swallow import Coconut


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    coconut = Coconut(
        [
            {
                "regular_fields": [
                    {"name": "date", "type": "DATE", "nullable": False},
                    {"name": "users", "type": "INT64", "nullable": False},
                    {"name": "prospects", "type": "INT64", "nullable": False},
                    {"name": "clients", "type": "INT64", "nullable": False},
                ],
                "delta_fields": {"prospects", "users", "clients"},
                "table_name": "user",
            }
        ]
    )

    operations = [migrations.RunPython(coconut.forward, coconut.backward)]
